# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"


# http://stackoverflow.com/a/26394449/370191
require 'yaml'
current_dir    = File.dirname(File.expand_path(__FILE__))
config        = YAML.load_file("#{current_dir}/config.yaml")


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "centos42f" do |centos42f|

    centos42f.vm.provider :digital_ocean do |provider, override|


      provider.client_id = config['digital_ocean_client_id']
      provider.region = config['digital_ocean_region']
      provider.token = config['digital_ocean_token']
      #provider.size = 4096mb
      provider.image = "centos-7-0-x64"


      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      override.ssh.private_key_path = config['private_key_path']
    end

    centos42f.vm.box = "digital_ocean"

    if Vagrant.has_plugin?("vagrant-vbguest")
      centos42f.vbguest.auto_update = true
    end

    centos42f.vm.network :forwarded_port, guest: 8443, host: 8443

    centos42f.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; then apt-get update; else yum -y update; fi; cd /vagrant; install/modules-for-vagrant.sh"
      #shell.inline = "echo 'class { \'alfresco\': alfresco_version=4.2.f domain_name=localhost }' > centos42f.pp"
    end

    centos42f.vm.provision :puppet do |puppet|
      puppet.manifests_path = ".."
      puppet.manifest_file  = "centos42f.pp"
      puppet.module_path = ["../modules"]
    end
  end

  config.vm.define "centos50x" do |centos50x|

    centos50x.vm.provider :digital_ocean do |provider, override|

        provider.client_id = config['digital_ocean_client_id']
    	override.ssh.private_key_path = config['private_key_path']
    	provider.region = config['digital_ocean_region']
    	provider.token = config['digital_ocean_token']

      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"
      #provider.size = 4096mb

    	provider.image = "centos-7-0-x64"
     	# provider.image = "ubuntu-15-04-x64"

    end

    centos50x.vm.box = "digital_ocean"

    if Vagrant.has_plugin?("vagrant-vbguest")
      centos50x.vbguest.auto_update = true
    end

    centos50x.vm.network :forwarded_port, guest: 8443, host: 8443

    centos50x.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; then apt-get update; else yum -y update; fi; cd /vagrant; install/modules-for-vagrant.sh"
    end

    centos50x.vm.provision :puppet do |puppet|
      puppet.manifests_path = ".."
      puppet.manifest_file  = "centos50x.pp"
      puppet.module_path = ["../modules"]
    end
  end



  config.vm.define "ubuntu42f" do |ubuntu42f|


    ubuntu42f.vm.provider :digital_ocean do |provider, override|

      provider.client_id = config['digital_ocean_client_id']
      override.ssh.private_key_path = config['private_key_path']
  	  provider.region = config['digital_ocean_region']
  	  provider.token = config['digital_ocean_token']

      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

      #provider.size = 4096mb

   	  provider.image = "ubuntu-15-04-x64"

    end

    #ubuntu42f.vm.box = "ubuntu/vivid64"
    ubuntu42f.vm.box = "digital_ocean"

    if Vagrant.has_plugin?("vagrant-vbguest")
      ubuntu42f.vbguest.auto_update = true
    end

    ubuntu42f.vm.network :forwarded_port, guest: 8443, host: 8443

    ubuntu42f.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; then apt-get update; else yum -y update; fi; cd /vagrant; install/modules-for-vagrant.sh"
      #shell.inline = "echo 'class { \'alfresco\': alfresco_version=4.2.f domain_name=localhost }' > ubuntu42f.pp"
    end

    ubuntu42f.vm.provision :puppet do |puppet|
      puppet.manifests_path = ".."
      puppet.manifest_file  = "ubuntu42f.pp"
      puppet.module_path = ["../modules"]
    end
  end



  config.vm.define "ubuntu50x" do |ubuntu50x|


    ubuntu50x.vm.provider :digital_ocean do |provider, override|

      provider.client_id = config['digital_ocean_client_id']
  	  override.ssh.private_key_path = config['private_key_path']
  	  provider.region = config['digital_ocean_region']
  	  provider.token = config['digital_ocean_token']


      override.vm.box = 'digital_ocean'
      override.vm.box_url = "https://github.com/smdahlen/vagrant-digitalocean/raw/master/box/digital_ocean.box"

      #provider.size = 4096mb

  	  #provider.image = "centos-7-0-x64"
   	  provider.image = "ubuntu-15-04-x64"

    end

    ubuntu50x.vm.box = "digital_ocean"

    if Vagrant.has_plugin?("vagrant-vbguest")
      ubuntu50x.vbguest.auto_update = true
    end

    ubuntu50x.vm.network :forwarded_port, guest: 8443, host: 8443

    ubuntu50x.vm.provision :shell do |shell|
      shell.inline = "OS=`cat /etc/issue | head -n1 | cut -f1 -d' '`; if [ \"$OS\" == \"Debian\" -o \"$OS\" == \"Ubuntu\" ]; then apt-get update; else yum -y update; fi; cd /vagrant; install/modules-for-vagrant.sh"
      #shell.inline = "echo 'class { \'alfresco\': alfresco_version=5.0.x domain_name=localhost }' > ubuntu50x.pp"
    end

    ubuntu50x.vm.provision :puppet do |puppet|
      puppet.manifests_path = ".."
      puppet.manifest_file  = "ubuntu50x.pp"
      puppet.module_path = ["../modules"]
    end
  end

end
